name: pr-agent

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]
    
permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: >-
       ${{ github.event.sender.type != 'Bot'
          && (github.event.issue.pull_request
             || (!github.event.issue.pull_request
                && (startsWith(github.event.comment.body, '/describe')
                   || startsWith(github.event.comment.body, '/review')
                   || startsWith(github.event.comment.body, '/improve')
                   || startsWith(github.event.comment.body, '/ask')
                   || startsWith(github.event.comment.body, '/update_changelog')
                   || startsWith(github.event.comment.body, '/similar_issue')
                   || startsWith(github.event.comment.body, '/help')
                   )
                )
             )
       }}
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: '日本語で記述してください。'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: '全て日本語で記述してください。'
