name: pr-agent

on:
#  pull_request:
#    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    if: >
      (github.event.sender.type != 'Bot'
        && (github.event_name == 'pull_request'
          || (github.event_name == 'issue_comment'
            && (contains(github.event.comment.body, '/describe')
              || contains(github.event.comment.body, '/review')
              || contains(github.event.comment.body, '/improve')
              || contains(github.event.comment.body, '/ask')
              || contains(github.event.comment.body, '/update_changelog')
              || contains(github.event.comment.body, '/similar_issue')
              || contains(github.event.comment.body, '/help')
            )
          )
        )
      )
    steps:
      - name: Checkout the Wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: List files in Wiki Repository
        run: ls wiki
        
      - name: Set up Wiki Info
        id: wiki_info
        run: |
          set_env_var_from_file() {
            local var_name=$1
            local file_path=$2
            local prompt=$(cat "$file_path")
            echo "${var_name}<<EOF" >> $GITHUB_ENV
            echo "prompt" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          }
          set_env_var_from_file "REVIEW_PROMPT" "./wiki/pr-agent-review-prompt.md"
          set_env_var_from_file "DESCRIBE_PROMPT" "./wiki/pr-agent-describe-prompt.md"
          set_env_var_from_file "IMPROVE_PROMPT" "./wiki/pr-agent-improve-prompt.md"

      - name: Run PR Agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # PR_AGENT settings (/review)
          PR_REVIEWER.extra_instructions: |
            ${{env.REVIEW_PROMPT}}

          # PR_DESCRIPTION settings (/describe)
          PR_DESCRIPTION.extra_instructions: |
            ${{env.DESCRIBE_PROMPT}}

          # PR_CODE_SUGGESTIONS settings (/improve)
          PR_CODE_SUGGESTIONS.extra_instructions: |
            ${{env.IMPROVE_PROMPT}}
