name: pr-agent

on:
#  pull_request:
#    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    if: >
      (github.event.sender.type != 'Bot'
        && (github.event_name == 'pull_request'
          || (github.event_name == 'issue_comment'
            && (contains(github.event.comment.body, '/describe')
              || contains(github.event.comment.body, '/review')
              || contains(github.event.comment.body, '/improve')
              || contains(github.event.comment.body, '/ask')
              || contains(github.event.comment.body, '/update_changelog')
              || contains(github.event.comment.body, '/similar_issue')
              || contains(github.event.comment.body, '/help')
            )
          )
        )
      )
    steps:
      - name: Run PR Agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PR_REVIEWER.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
#          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "全て日本語で記述してください。"
